databases:
  - name: trader-go-postgres
    databaseName: trader_go_postgres
    user: trader_go_postgres_user

services:
  - type: web
    name: trader_go
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn trader_go.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: trader_go.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "trader-go-backend.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
